### ISSUE TITLE
CPK + Postgis. CPK + SERIAL columns in primary key

### ISSUE THREAD

**Issue by glytch** [composite-primary-keys/composite_primary_keys#174]
https://github.com/glytch/composite_primary_keys_test_app

I've made a minimal rails app here that demonstrates the issues

First, whenever you try to update a record that's using composite primary keys as well as postgis data types an exception is raised.

```
NoMethodError:         undefined method `to_sym' for nil:NilClass
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:671:in `type_to_sql'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:467:in `type_to_sql'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/connection_adapters/postgresql/quoting.rb:21:in `quote'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/to_sql.rb:597:in `quote'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/to_sql.rb:510:in `visit_Arel_Nodes_Assignment'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/visitor.rb:22:in `visit'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/to_sql.rb:103:in `block in visit_Arel_Nodes_UpdateStatement'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/to_sql.rb:103:in `map'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/to_sql.rb:103:in `visit_Arel_Nodes_UpdateStatement'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/visitor.rb:22:in `visit'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/visitors/visitor.rb:5:in `accept'
        /usr/local/lib/ruby/gems/1.9.1/gems/arel-4.0.1/lib/arel/tree_manager.rb:21:in `to_sql'
        /usr/local/lib/ruby/gems/1.9.1/gems/composite_primary_keys-6.0.1/lib/composite_primary_keys/persistence.rb:65:in `update_record'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/persistence.rb:477:in `create_or_update'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/callbacks.rb:302:in `block in create_or_update'
        /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:403:in `_run__1249828579626780228__save__callbacks'
        /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/callbacks.rb:302:in `create_or_update'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/persistence.rb:128:in `save!'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/validations.rb:57:in `save!'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `block in save!'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:200:in `transaction'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/transactions.rb:209:in `transaction'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
        /usr/local/lib/ruby/gems/1.9.1/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `save!'
```

Second. If you use a SERIAL column as part of your composite key you end up with the issue described here

https://groups.google.com/forum/#!topic/compositekeys/PES6O2B-dWI

The application includes models using a work around that makes this work. As well as a model without the work around that fails due to the bug described

**Comment by onurrro** [comment]
Did somebody manage to fix that for activerecord 4.0.2? I'm getting that error now and have no solution...

**Comment by cfis** [comment]
Did you try the posted monkey patch?  Happy to take a patch on the 4.0.2 branch if you'd like to provide one.  Dev effort is on 4.2.

**Comment by cfis** [comment]
Because this is now so old, I'm going to go ahead and close it.
