### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by hjames9** [composite-primary-keys/composite_primary_keys#266]
Default version of composite_primary_keys gem installed with Rails 4.2 is version 6.0.5, which doesn't work with 4.2.  However the branch "ar_4.2.x" appears to work correctly with the new rails version.

**Comment by kirikak2** [comment]
I am trying update rails 4.2.0 on "ar_4.2.x" branch.
change gemspec and fix broken tests.

Failed tests are as follows.

```
  1) Failure:
TestAttributes#test_brackets [/home/t-maki/rails/composite_primary_keys/test/test_attributes.rb:24]:
Expected: nil
  Actual: [1, 1]


  2) Error:
TestSerialization#test_json:
TypeError: ["department_id", "location_id"] is not a symbol
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `block in serializable_hash'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `each'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `serializable_hash'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/serialization.rb:17:in `serializable_hash'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serializers/json.rb:99:in `as_json'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
    /home/t-maki/rails/composite_primary_keys/test/test_serialize.rb:8:in `test_json'


  3) Error:
TestSerialization#test_serializable_hash:
TypeError: ["department_id", "location_id"] is not a symbol
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `block in serializable_hash'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `each'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/serialization.rb:108:in `serializable_hash'
    /home/t-maki/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/serialization.rb:17:in `serializable_hash'
    /home/t-maki/rails/composite_primary_keys/test/test_serialize.rb:13:in `test_serializable_hash'

149 runs, 378 assertions, 1 failures, 2 errors, 0 skips
rake aborted!
```

I'll send PR that fix broken tests. ( This PR includes #263 commit)
But this fix is not complete.
We should need support StatementCache on CPK and add test cases.

**Comment by cfis** [comment]
Thanks for the patch and with tests!  Anyway you can use the existing fixtures though for the new tests?  The number of fixtures is getting a bit large, I'd like to not add to them if possible.

**Comment by cfis** [comment]
Rails support has been merged to master.  I see 1 failing test, but will have separate ticket for that.
