### ISSUE TITLE
Lots of records + has_many + delete = SystemStackError

### ISSUE THREAD

**Issue by libc** [composite-primary-keys/composite_primary_keys#296]
Hello

Because https://github.com/composite-primary-keys/composite_primary_keys/blob/38533b8990cccaf7e7feae653a05bbcc561513c3/lib/composite_primary_keys/associations/has_many_association.rb#L28-L39 constructs a big tree, it causes SystemStackError deep down in Arel when number of records is big enough.

It happens even when the table has primary key with 1 column only.

```
➜  /tmp  ruby composite_overflow.rb        
==  TestMigration: migrating ==================================================
-- create_table(:as)
   -> 0.0019s
-- create_table(:bs)
   -> 0.0004s
==  TestMigration: migrated (0.0025s) =========================================

/Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash': stack level too deep (SystemStackError)
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/unary.rb:13:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/unary.rb:13:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/unary.rb:13:in `hash'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/arel-6.0.0/lib/arel/nodes/binary.rb:19:in `hash'
     ... 10064 levels...
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:373:in `replace'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/collection_association.rb:47:in `writer'
    from /Users/eugene/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:123:in `bs='
    from composite_overflow.rb:37:in `<main>'
➜  /tmp  ruby composite_overflow.rb 'do-not-compose'
==  TestMigration: migrating ==================================================
-- create_table(:as)
   -> 0.0015s
-- create_table(:bs)
   -> 0.0004s
==  TestMigration: migrated (0.0021s) =========================================

👍🏼
```

Code to reproduce

``` ruby
require 'active_record'

if ARGV[0] != 'do-not-compose'
  require 'composite_primary_keys'
end

ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'
#ActiveRecord::Base.logger = Logger.new(STDERR)

class TestMigration < ActiveRecord::Migration
  def change
    create_table :as do |t|
    end

    create_table :bs do |t|
      t.references :a
    end
  end
end

TestMigration.migrate(:up)

class A < ActiveRecord::Base
  has_many :bs
end

class B < ActiveRecord::Base
end

a = A.create

# over 9000
a.bs = 9001.times.map { B.new }

a.save!

a.bs = []
a.save!

puts "👍🏼"
```

Cheers

**Comment by cfis** [comment]
So that also happens in a non-CPK model?

**Comment by libc** [comment]
Yep. In my ruby code example the gem is optional. If I don't require it, it works, if I require it fails.

Found this issue with models that do not have CPK
