### ISSUE TITLE
ArgumentError (wrong number of arguments calling `_field_changed?` (2 for 3))

### ISSUE THREAD

**Issue by sanelson2000** [composite-primary-keys/composite_primary_keys#301]
Using JRuby 1.7.20 and activerecord-jdbc-adapter 1.3.16

Attempting to upgrade to Rails 4.2.1 and composite_primary_keys 8.1.0.  I keep running into the following error:
```
ArgumentError (wrong number of arguments calling `_field_changed?` (2 for 3)):
  activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:114:in `save_changed_attribute'
  composite_primary_keys (8.1.0) lib/composite_primary_keys/attribute_methods/dirty.rb:18:in `write_attribute'
  activerecord (4.2.1) lib/active_record/attribute_methods/write.rb:50:in `__temp__9637f556e61626c65646='
  activerecord (4.2.1) lib/active_record/scoping.rb:26:in `populate_with_current_scope_attributes'
  org/jruby/RubyHash.java:1341:in `each'
  activerecord (4.2.1) lib/active_record/scoping.rb:25:in `populate_with_current_scope_attributes'
  activerecord (4.2.1) lib/active_record/scoping.rb:32:in `initialize_internals_callback'
  activerecord (4.2.1) lib/active_record/core.rb:277:in `initialize'
  activerecord (4.2.1) lib/active_record/inheritance.rb:61:in `new'
```

**Comment by cfis** [comment]
Hmm, do you have some other monkey patch?  _field_changed does take two arguments:

https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/attribute_methods/dirty.rb#L140

Charlie

**Comment by sanelson2000** [comment]
Sorry... This appears to be an issue with activerecord-oracle_enhanced-adaptor, not composite_primary_keys.

https://github.com/rsim/oracle-enhanced/issues/477

Closing this issue.
