### ISSUE TITLE
5.0.* / Setting association via model constructor

### ISSUE THREAD

**Issue by brent-clintel** [composite-primary-keys/composite_primary_keys#308]
Just say we have the following setup:
```ruby
class Person
    # Note: person has an id column that should be considered the primary key in most instances (but not all)
    attr_accessor :firstname, :lastname
end

class PersonRelatedRecord
    belongs_to :person, :foreign_key => [:fname, :lname], :primary_key => [:first_name, :last_name]
    attr_accessor :person, :fname, :lname
end
```

and then we try to initialise PersonRelatedRecord with:
```ruby
person = Person.new(:first_name => 'Joe', :last_name => 'Smeg')
record = PersonRelatedRecord.new(:person => person)
record.save!
```

What I am expecting to happen is, when `PersonRelatedRecord` is saved, it gets the values from the person instance from the columns specified in `:primary_key` and saves them to the columns specified by `:foreign_key`.

However, what I am actually getting is the following Error:

```
Exception: TypeError: [:first_name, :last_name] is not a symbol
--
 0: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/autosave_association.rb:415:in `save_belongs_to_association'
 1: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/autosave_association.rb:209:in `block in add_autosave_association_callbacks'
 2: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/autosave_association.rb:161:in `instance_eval'
 3: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/autosave_association.rb:161:in `block in define_non_cyclic_method'
 4: ./vendor/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:429:in `_run__1551146335103869047__save__854819673309113942__callbacks'
 5: ./vendor/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
 6: ./vendor/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
 7: ./vendor/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
 8: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:264:in `create_or_update'
 9: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:104:in `save!'
10: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
11: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
12: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `block in save!'
13: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
14: ./vendor/ruby/2.1.0/gems/activerecord-sqlserver-adapter-3.2.12/lib/active_record/connection_adapters/sqlserver/database_statements.rb:52:in `block in transaction'
15: ./vendor/ruby/2.1.0/gems/activerecord-sqlserver-adapter-3.2.12/lib/active_record/connection_adapters/sqlserver/core_ext/database_statements.rb:37:in `transaction_with_retry_deadlock_victim'
16: ./vendor/ruby/2.1.0/gems/activerecord-sqlserver-adapter-3.2.12/lib/active_record/connection_adapters/sqlserver/database_statements.rb:52:in `transaction'
17: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
18: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
19: ./vendor/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
20: (pry):116:in `<main>'
```
I get that `Person` doesnt have `self.primary_keys`, but it shouldn't need to, we are telling the belongs_to relationship what primary key to use.  In actual fact, other models use `Person#id` so setting ``self.primary_keys` would actually be incorrect.

**Comment by cfis** [comment]
Does it work by setting primary keys on Person?

**Comment by brent-clintel** [comment]
If `Person.primary_keys = :firstname, :lastname` is set, then it does work.

**Comment by cfis** [comment]
Sorry for no response on this.  By 5.0.* you mean CPK version 5.0.0?  So back on ActiveRecord 3.2?  That's not supported anymore.  Happy to take a patch though if you'd like to send one in.
