### ISSUE TITLE
Rails 4.2.5 with latest from master causing postgresql column does not exist error on insert

### ISSUE THREAD

**Issue by therealjessesanford** [composite-primary-keys/composite_primary_keys#331]
composite_primary_keys > 8.0.0 including the latest from master branch does not seem to be compatible with rails >= 4.2.4

activerecord (4.2.5)
activemodel (= 4.2.5)
activesupport (= 4.2.5)
arel (~> 6.0)

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "connection_id,parameter_name" does not exist
LINE 1: ..._id", "parameter_name") VALUES ($1, $2) RETURNING "connectio...
                                                             ^
: INSERT INTO "guacamole_connection_parameter" ("connection_id", "parameter_name") VALUES ($1, $2) RETURNING "connection_id,parameter_name"
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_cache'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:64:in `insert'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/persistence.rb:524:in `_create_record'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/counter_cache.rb:139:in `_create_record'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/locking/optimistic.rb:75:in `_create_record'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:132:in `_create_record'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `block in _create_record'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
... 25 levels...
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/persistence.rb:34:in `create'
	from (irb):11
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/app_rails_loader.rb:45:in `require'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/app_rails_loader.rb:34:in `loop'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/lib/rails/cli.rb:5:in `<top (required)>'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/bin/rails:9:in `require'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/gems/railties-4.2.5/bin/rails:9:in `<top (required)>'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/bin/rails:23:in `load'
	from /Users/jessesanford/workspace/stn_middleware/vendor/ruby/2.2.0/bin/rails:23:in `<main>'irb(main):016:0>
```

Model file in question:

```
require 'composite_primary_keys'
class Guacamole::ConnectionParameter < GuacamoleDbBase
  def self.table_name
    'guacamole_connection_parameter'
  end

  self.primary_keys = :connection_id, :parameter_name

  belongs_to :connection, class_name: 'Guacamole::Connection', inverse_of: :connection_parameters
end
```

**Comment by therealjessesanford** [comment]
It seems that this issue is because I am not using bundler. Where should the requires happen in frameworks other than rails?

**Comment by cfis** [comment]
CPK need to be required after activerecord has been loaded since it overrides activerecord.
