### ISSUE TITLE
Issue with incorrectly trying to resolve polymorphic relationships

### ISSUE THREAD

**Issue by piotrb** [composite-primary-keys/composite_primary_keys#334]
Error: uninitialized constant RequirementQualifier::Qualifier

In the spec the code just calls create on a model, obviously a whole bunch of other stuff happens .. 

RequirementQualifier is an AR
Qualifier .. doesn't exist .. :qualifier is the name of a polymorphic relationship on RequirementQualifier

trace:

```
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/inheritance.rb:158:in `compute_type'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/reflection.rb:295:in `compute_class'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/reflection.rb:291:in `klass'
     # ./vendor/cache/composite_primary_keys-bf53dce8df75/lib/composite_primary_keys/associations/has_many_through_association.rb:22:in `delete_records'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:525:in `remove_records'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:518:in `block in delete_or_destroy'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:518:in `delete_or_destroy'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:268:in `delete'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:538:in `replace_records'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:373:in `block in replace'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:182:in `transaction'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:373:in `replace'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/collection_association.rb:47:in `writer'
     # /Users/piotr/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/associations/builder/association.rb:123:in `for_employee_types='
     # ./spec/models/requirement_spec.rb:95:in `block (6 levels) in <top (required)>'
```

**Comment by piotrb** [comment]
Maybe related to #285

**Comment by cfis** [comment]
Hmm, guess there isn't a test then to check that code then.  Want to add one?
