### ISSUE TITLE
NoMethodError: undefined method `old_attribute_value'  error on master

### ISSUE THREAD

**Issue by sandric** [composite-primary-keys/composite_primary_keys#350]
Hey there. It looks like composite_primary_keys fails on master, I guess thats 5.0.0.beta3 issue, here's ```rake db:reset``` after adding gem to gemfile error log:

```
NoMethodError: undefined method `old_attribute_value' for #<ActiveRecord::InternalMetadata:0x007fc3606c4be0>
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/bundler/gems/composite_primary_keys-c324f6e4fd29/lib/composite_primary_keys/attribute_methods/dirty.rb:14:in `write_attribute'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/attribute_methods/write.rb:20:in `__temp__b65697='
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:46:in `public_send'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:39:in `each'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activemodel-5.0.0.beta3/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/core.rb:310:in `initialize'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/inheritance.rb:65:in `new'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/inheritance.rb:65:in `new'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/relation.rb:125:in `block in new'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/relation.rb:351:in `scoping'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/relation.rb:125:in `new'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/relation.rb:172:in `first_or_initialize'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/querying.rb:5:in `first_or_initialize'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/internal_metadata.rb:22:in `[]='
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/activerecord-5.0.0.beta3/lib/active_record/railties/databases.rake:7:in `block (2 levels) in <top (required)>'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/railties-5.0.0.beta3/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/railties-5.0.0.beta3/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
/Users/sandric/projects/ruby/yizhack/vendor/bundle/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:environment:set
(See full trace by running task with --trace)
```

**Comment by sandric** [comment]
Yes, it looks like [that](https://github.com/rails/rails/blob/v5.0.0.beta2/activerecord/lib/active_record/attribute_methods/dirty.rb) is removed a lot of old methods in Dirty module..

**Comment by codeodor** [comment]
I'm working on a pull request to add support for Rails 5 in #348.

**Comment by sandric** [comment]
@codeodor  Oh, thats just great, thx!
