### ISSUE TITLE
 ArgumentError has occurred in rails5.0.0.rc1

### ISSUE THREAD

**Issue by pocari** [composite-primary-keys/composite_primary_keys#356]
Using composite_primary_keys with rails5.0.0.rc1, `ArgumentError` has occurred.

```
$ bundle exec rake mysql:rebuild_database
Using native MySQL
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/var/data/vendor/bundle/ruby/2.2.0/gems/activerecord-5.0.0.rc1/lib/active_record/connection_adapters/abstract/connection_pool.rb:842:in `establish_connection'
/var/data/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:25:in `establish_connection'
/var/data/test/connections/native_mysql/connection.rb:15:in `establish_connection'
/var/data/test/connections/native_mysql/connection.rb:17:in `<top (required)>'
/var/data/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
/var/data/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
/var/data/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/data/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
/var/data/tasks/databases/mysql.rake:39:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/usr/local/bundle/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => mysql:rebuild_database => mysql:drop_database => mysql:load_connection
(See full trace by running task with --trace)
```

I have worked around by the following code.
https://github.com/pocari/composite_primary_keys/commit/22528f4ae1015284fa5804d04cf7af4df86dbe7c

Are there any plans to fix this problem ?

**Comment by Z3r0Sum** [comment]
👍  - Please

**Comment by pocari** [comment]
@Z3r0Sum my branch has passed all tests in `postgresql`, `mysql`, `sqlite3`.  I will send PR.

**Comment by djantzen** [comment]
Will there be a new release available soon with this patch? We are also encountering the problem with the 9.0.0.beta1 build of composite-primary-key and rails 5 rc2.

Thanks, David

**Comment by scottbarrow** [comment]
👍 also looking for an eta on the release with this merge?

**Comment by cfis** [comment]
Closing in favor of #362.
