### ISSUE TITLE
undefined method `val' for nil:NilClass

### ISSUE THREAD

**Issue by scottbarrow** [composite-primary-keys/composite_primary_keys#373]
Rails 4.2.6, Ruby 2.2

```
#gemfile.lock
composite_primary_keys (8.1.4)
      activerecord (~> 4.2.0)
...
activerecord (4.2.6)
```

**Exception**
![cpk](https://cloud.githubusercontent.com/assets/5571736/21412124/aef0dc2c-c7a2-11e6-93a2-12939be0a7b9.png)

**Stack**
```
composite_primary_keys (8.1.4) lib/composite_primary_keys/relation.rb:42:in `block (2 levels) in where_values_hash'
composite_primary_keys (8.1.4) lib/composite_primary_keys/relation.rb:38:in `fetch'
composite_primary_keys (8.1.4) lib/composite_primary_keys/relation.rb:38:in `block in where_values_hash'
composite_primary_keys (8.1.4) lib/composite_primary_keys/relation.rb:36:in `map'
composite_primary_keys (8.1.4) lib/composite_primary_keys/relation.rb:36:in `where_values_hash'
activerecord (4.2.6) lib/active_record/relation.rb:580:in `scope_for_create'
activerecord (4.2.6) lib/active_record/scoping/named.rb:39:in `scope_attributes'
activerecord (4.2.6) lib/active_record/scoping.rb:25:in `populate_with_current_scope_attributes'
activerecord (4.2.6) lib/active_record/scoping.rb:32:in `initialize_internals_callback'
activerecord (4.2.6) lib/active_record/core.rb:277:in `initialize'
activerecord (4.2.6) lib/active_record/inheritance.rb:61:in `new'
activerecord (4.2.6) lib/active_record/inheritance.rb:61:in `new'
devise (4.2.0controllers) devise/sessions_controller.rb:9:in `new'
...
```
investigating further, but if anyone has any experience/input?

**Comment by cfis** [comment]
I'd guess this is an application bug, but would need to know more info to know for sure (meaning a test case).  Reopen if you'd like if you have more information to help track down.
