### ISSUE TITLE
Missing overrided version of ActiveRecord::Associations::CollectionAssociation#ids_reader

### ISSUE THREAD

**Issue by pustomytnyk** [composite-primary-keys/composite_primary_keys#390]
When I'm trying to call `model.association_ids` for association with composite key it fails with `<keys array> is not a symbol nor a string` at line

`activerecord (5.0.1) lib/active_record/associations/collection_association.rb:60:in block in ids_reader`
```
    if loaded?
      load_target.map do |record|
fail => record.send(reflection.association_primary_key)
      end
```

**Comment by pustomytnyk** [comment]
I don't know what are correct test cases for this feature

**Comment by cfis** [comment]
Ok - do you have a traceback?

**Comment by pustomytnyk** [comment]
@cfis, it occurs in https://github.com/thoughtbot/administrate/blob/master/app/views/fields/has_many/_form.html.erb#L27 
on line `<%= options_for_select(field.associated_resource_options, field.selected_options) %>`)

Each element in `field.associated_resource_options` array has structure like `[some_my_string, composite_id]`

then traceback is:
```
activerecord (5.0.1) lib/active_record/associations/collection_association.rb:60:in `block in ids_reader'
activerecord (5.0.1) lib/active_record/associations/collection_association.rb:59:in `map'
activerecord (5.0.1) lib/active_record/associations/collection_association.rb:59:in `ids_reader'
activerecord (5.0.1) lib/active_record/associations/builder/collection_association.rb:56:in `authors_source_ids'
actionview (5.0.1) lib/action_view/helpers/tags/base.rb:28:in `public_send'
actionview (5.0.1) lib/action_view/helpers/tags/base.rb:28:in `value'
actionview (5.0.1) lib/action_view/helpers/tags/select.rb:16:in `block in render'
actionview (5.0.1) lib/action_view/helpers/tags/select.rb:16:in `fetch'
actionview (5.0.1) lib/action_view/helpers/tags/select.rb:16:in `render'
actionview (5.0.1) lib/action_view/helpers/form_options_helper.rb:163:in `select'
actionview (5.0.1) lib/action_view/helpers/form_options_helper.rb:817:in `select'
```

**Comment by cfis** [comment]
Pull request 391 merged.
