### ISSUE TITLE
CPK Breaks eager loading belongs_to association ?

### ISSUE THREAD

**Issue by tommyalvarez** [composite-primary-keys/composite_primary_keys#406]
Given the following models:

```
Class PurchaseOrderLine < SecondBase::Base
self.table_name = "SegDetV"
self.primary_keys = "sdv_id", "sdvsuc_cod", "sdvemp_codigo"

...
belongs_to :bejerman_product, class_name: Bejerman::Product.model_name.name, foreign_key: ["sdvart_codgen", "sdvart_codele1", "sdvart_codele2", "sdvart_codele3"]
...
end
```

```
class Bejerman::Product < SecondBase::Base
  #
  # Model Config
  #
  self.table_name = "Articulos"
  self.primary_keys = "art_codgen", "art_codele1", "art_codele2","art_codele3"
...
belongs_to :bejerman_product_type, class_name: Bejerman::ProductType.model_name.name, foreign_key: "artcla_cod"
...
end

```
```
class Bejerman::ProductType < SecondBase::Base
  #
  # Model Config
  #
  self.table_name = "ClasArt"
  self.primary_key = "cla_Cod"

...
end
```

By eager loading the whole association _PurchaseOrderLine.scopes.includes(bejerman_product: :bejerman_product_type),_ it fails with the weird error: _undefined method each for nil_. I managed to get the backtrace of the exception:

`["/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/composite_primary_keys-9.0.6/lib/composite_primary_keys/associations/preloader/association.rb:44:in `block in associated_records_by_owner'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/composite_primary_keys-9.0.6/lib/composite_primary_keys/associations/preloader/association.rb:43:in `each'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/composite_primary_keys-9.0.6/lib/composite_primary_keys/associations/preloader/association.rb:43:in `associated_records_by_owner'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/activerecord-5.0.2/lib/active_record/associations/preloader/singular_association.rb:9:in `preload'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/activerecord-5.0.2/lib/active_record/associations/preloader/association.rb:19:in `run'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/activerecord-5.0.2/lib/active_record/associations/preloader.rb:151:in `block (2 levels) in preloaders_for_one'", "/home/tommy/.rvm/gems/ruby-2.4.0@igalplan/gems/activerecord-5.0.2/lib/active_record/associations/preloader.rb:149
`
Am i doing something wrong or the gem has a bug? Using version  9.0.6 and rails 5.0.2.

Thanks

**Comment by tommyalvarez** [comment]
Nevermind, i fixed it. The problem was in my definition of the composity primary keys of the Bejerman::ProductType model, it should have been downcase
