### ISSUE TITLE
Rails 5.1 undefined method `apply_scope' for #<ActiveRecord::Associations::AssociationScope

### ISSUE THREAD

**Issue by jeznag** [composite-primary-keys/composite_primary_keys#419]
I'm getting this error after upgrading to Rails 5.1 and can't figure out what's wrong:

`undefined method `apply_scope' for #<ActiveRecord::Associations::AssociationScope`

Relevant code is:

```
def set_site
   @site = current_account.sites.active.find(params[:id])
   redirect_to sites_path if @site.nil?
   @site
end
```

Model:
```
class Site < ApplicationRecord
    belongs_to  :account
    scope :active, (-> { where(workflow_state: 'active') })
    # ....
end
```

Full Stack Trace:
```
composite_primary_keys (10.0.1) lib/composite_primary_keys/associations/association_scope.rb:35:in `block in last_chain_scope'
composite_primary_keys (10.0.1) lib/composite_primary_keys/associations/association_scope.rb:33:in `each'
composite_primary_keys (10.0.1) lib/composite_primary_keys/associations/association_scope.rb:33:in `last_chain_scope'
activerecord (5.1.0) lib/active_record/associations/association_scope.rb:126:in `add_constraints'
/usr/local/bundle/bundler/gems/activemodel-associations-8dab1043fc77/lib/active_model/associations/association_scope_extension.rb:10:in `add_constraints'
activerecord (5.1.0) lib/active_record/associations/association_scope.rb:28:in `scope'
activerecord (5.1.0) lib/active_record/associations/association_scope.rb:5:in `scope'
activerecord (5.1.0) lib/active_record/associations/association.rb:97:in `association_scope'
activerecord (5.1.0) lib/active_record/associations/collection_proxy.rb:1162:in `association_scope'
activerecord (5.1.0) lib/active_record/associations/collection_proxy.rb:1131:in `method_missing'
app/controllers/sites_controller.rb:215:in `set_site'
```

**Comment by manicmaniac** [comment]
Same. downgrade to 10.0.0 fixes it.

**Comment by cfis** [comment]
You need to be on ActiveRecord 5.1.4 since this was an activerecord change:
https://github.com/rails/rails/commit/8f5e8886179f7cbc162f546a7d73f55d9296e06c

10.0.0 doesn't really "fix it" - that code is incorrect.
