### ISSUE TITLE
_update_record ArgumentError with Rails 5.2.0

### ISSUE THREAD

**Issue by ntippie** [composite-primary-keys/composite_primary_keys#440]
When using Rails 5.2.0 with CPK 11.0.0.rc2, I am getting this error while creating the database:

```ruby
ArgumentError: wrong number of arguments (given 2, expected 3)
/usr/local/bundle/gems/composite_primary_keys-11.0.0.rc2/lib/composite_primary_keys/persistence.rb:23:in `_update_record'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/persistence.rb:695:in `_update_row'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/locking/optimistic.rb:80:in `_update_row'
/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/persistence.rb:718:in `_update_record'
/usr/local/bundle/gems/composite_primary_keys-11.0.0.rc2/lib/composite_primary_keys/locking/optimistic.rb:5:in `_update_record'
...
```

I traced the issue back to rails/rails@6932998 and rails/rails@3798435.

**Comment by erkie** [comment]
I've made a fork that fixes this issue: https://github.com/feederco/composite_primary_keys commit: https://github.com/feederco/composite_primary_keys/commit/263f1c4aa2d8592d9a045805d648f67c1f4d5cae

However, I do not know if this is the most optimal solution.
