### ISSUE TITLE
undefined local variable or method `always_initialized'

### ISSUE THREAD

**Issue by kevgrig** [composite-primary-keys/composite_primary_keys#446]
Rails 5.1.6 [removed `always_initialized`](https://github.com/rails/rails/commit/1fd67501ce8b55bf9dc42efb119d3ca395c5363c) which causes the following error upgrading to 5.1.6 (see also https://github.com/rails/rails/issues/32385):

```
/home/kevin/.gem/ruby/bundler/gems/composite_primary_keys-9b44d3ee754f/lib/composite_primary_keys/attribute_set/builder.rb:10:in `build_from_database': undefined local variable or method `always_initialized' for #<ActiveRecord::AttributeSet::Builder:0x000056551e7d08b0> (NameError)
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/persistence.rb:68:in `instantiate'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/result.rb:55:in `block in each'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/result.rb:55:in `each'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/result.rb:55:in `each'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/querying.rb:50:in `map'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/querying.rb:50:in `block in find_by_sql'
        from /home/kevin/.gem/ruby/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/querying.rb:49:in `find_by_sql'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/relation.rb:678:in `exec_queries'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/relation.rb:546:in `load'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/relation.rb:255:in `records'
        from /home/kevin/.gem/ruby/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each' [...]
```

Workaround in Gemfile:

    gem "rails", ">=5.1.5", "<5.1.6"

**Comment by jkowens** [comment]
This was also backported to Rails 5.0.7, so it is currently broken too.

**Comment by jkowens** [comment]
Just noticed this was already reported in #435 and #437.
