### ISSUE TITLE
rails 5.2.1 update

### ISSUE THREAD

**Issue by S1azZy** [composite-primary-keys/composite_primary_keys#458]
In rails 5.2.1 the code was changed https://github.com/rails/rails/commit/cad0b7d91dbc5abf4b0d7fdbcf2d0620557a3b0f

and it raise errors like this

```
Exception: NoMethodError: undefined method `touch_updates' for #<Class:0x00007f9208030268>
--
0: /Users/a.tselovalnikov/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
1: /Users/a.tselovalnikov/.rvm/gems/ruby-2.5.1/gems/composite_primary_keys-11.0.3/lib/composite_primary_keys/counter_cache.rb:14:in `update_counters'
2: /Users/a.tselovalnikov/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/locking/optimistic.rb:156:in `update_counters'
3: /Users/a.tselovalnikov/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/persistence.rb:506:in `increment!'
4: /Users/a.tselovalnikov/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:336:in `block in increment!'
```

I'm sure there are still critical changes

**Comment by kingdonb** [comment]
This could be the same issue described in #455 or something else?

We are doing a big update project for our APIs, and several new projects that all need to use composite primary keys.  If I can get these issues all resolved, I will gladly shepherd/steward the PRs back into the repo master branch.

**Comment by natematykiewicz** [comment]
I know the issue in #455 is specifically about a has_one association. This one seems to have to do with updating a counter cache (based on the backtrace).

The issue here is that this line in CPK is no longer correct, as of the commit @S1azZy referenced above.
https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/counter_cache.rb#L14
