### ISSUE TITLE
Error on calling private method aliases with rails > 5.2

### ISSUE THREAD

**Issue by jklimke** [composite-primary-keys/composite_primary_keys#459]
Hi there. I noticed the following error after upgrading to 11.0.3.

It seems that recent changes using a private method.

```
Error
private method `aliases' called for #<ActiveRecord::Associations::JoinDependency:0x000000131b15f8>

Stacktrace
private method `aliases' called for #<ActiveRecord::Associations::JoinDependency:0x000000131b15f8> (NoMethodError)
NoMethodError:
private method `aliases' called for #<ActiveRecord::Associations::JoinDependency:0x000000131b15f8>
/home/jenkins/.rvm/gems/ruby-2.3.3/gems/composite_primary_keys-11.0.3/lib/composite_primary_keys/relation/finder_methods.rb:21:in `apply_join_dependency'
./spec/models/real_attribute_spec.rb:18:in `block (4 levels) in <top (required)>'
/home/jenkins/.rvm/gems/ruby-2.3.3/gems/composite_primary_keys-11.0.3/lib/composite_primary_keys/relation/batches.rb:40:in `block in in_batches'
/home/jenkins/.rvm/gems/ruby-2.3.3/gems/composite_primary_keys-11.0.3/lib/composite_primary_keys/relation/batches.rb:18:in `loop'
/home/jenkins/.rvm/gems/ruby-2.3.3/gems/composite_primary_keys-11.0.3/lib/composite_primary_keys/relation/batches.rb:18:in `in_batches'
./spec/models/real_attribute_spec.rb:17:in `block (3 levels) in <top (required)>'    
```

**Comment by kingdonb** [comment]
I just encountered this too.  The code that triggered the issue is a "where" on an association that does "eager_load" through some composite primary key associations.  It worked fine against Rails 5.2.0, but last night I tried upgrading to 5.2.1 and hit this error exactly.

I think I can understand the issue, I didn't even consider that it had something to do with my composite primary keys.  I guess I should get used to this...
