### ISSUE TITLE
Error with activerecord-sqlserver-adapter on ar_5.1.x branch

### ISSUE THREAD

**Issue by kevgrig** [composite-primary-keys/composite_primary_keys#465]
I've been using composite_primary_keys like so in [my Gemfile](https://github.com/myplaceonline/myplaceonline_rails/blob/master/Gemfile):

```
gem "composite_primary_keys", github: "composite-primary-keys/composite_primary_keys", branch: "ar_5.1.x"
```

I just upgraded to the latest gems (`bin/bundle update`) and received this exception:

```
Traceback (most recent call last):
        29: from bin/rails:4:in `<main>'
        28: from bin/rails:4:in `require'
        27: from /usr/share/gems/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
        26: from /usr/share/gems/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
        25: from /usr/share/gems/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
        24: from /usr/share/gems/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        23: from /usr/share/gems/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        22: from /usr/share/gems/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        21: from /usr/share/gems/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
        20: from /usr/share/gems/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
        19: from /usr/share/gems/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        18: from /usr/share/gems/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `require'
        17: from /work/myplaceonline/src/myplaceonline/src/myplaceonline_rails/config/application.rb:14:in `<top (required)>'
        16: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
        15: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
        14: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
        13: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
        12: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
        11: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        10: from /home/kevin/.gem/ruby/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
         9: from /usr/share/gems/bundler/gems/composite_primary_keys-20c25f41e455/lib/composite_primary_keys.rb:115:in `<top (required)>'
         8: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
         7: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
         6: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
         5: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
         4: from /usr/share/gems/bundler/gems/composite_primary_keys-20c25f41e455/lib/composite_primary_keys/arel/sqlserver.rb:1:in `<top (required)>'
         3: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
         2: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
         1: from /usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/usr/share/gems/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- activerecord-sqlserver-adapter (LoadError)
```

I worked around this issue by pointing to the commit before the most recent sqlserver commits:

```
gem "composite_primary_keys", github: "composite-primary-keys/composite_primary_keys", branch: "ar_5.1.x", ref: "3a29a1b7b02b7fef6b7f8a47f8deeb0f29d89f52"
```

**Comment by kevgrig** [comment]
@cfis No activerecord-sqlserver-adapter in my Gemfile. Full file: https://github.com/myplaceonline/myplaceonline_rails/blob/master/Gemfile

**Comment by cfis** [comment]
I see. Yeah that looks like a bug for sure. The file  composite_primary_keys/lib/composite_primary_keys/arel/sqlserver.rb should not automatically be loaded.
