### ISSUE TITLE
Polymorphic association does not support to compute class

### ISSUE THREAD

**Issue by moiristo** [composite-primary-keys/composite_primary_keys#491]
In Rails 5.2 and up, you cannot call `klass` on a through reflection; it will return the mentioned error. [CPK does this anyway](https://github.com/composite-primary-keys/composite_primary_keys/blob/55e9e51d5d0ca546184afb48939884a2207dcdc0/lib/composite_primary_keys/associations/through_association.rb#L8). When removing records from a hm through association, errors will occur when records are removed on removing records from the association.

As an example, consider the following application records:

```ruby
class Property < ApplicationRecord; end
class Facility < Property; end

class Todo < ApplicationRecord
  belongs_to :property, polymorphic: true, required: true
end

class User < ApplicationRecord
  has_many :todos
  has_many :facilities, through: :todos, source: :property, source_type: 'Facility'
end
```

When clearing facilities of a user that has some facilities, for example using `user.facility_ids = []`, the error will occur with the following trace:

```
activerecord (5.2.3) lib/active_record/reflection.rb:420:in `compute_class'
activerecord (5.2.3) lib/active_record/reflection.rb:379:in `klass'
composite_primary_keys (11.2.0) lib/composite_primary_keys/associations/through_association.rb:8:in `construct_join_attributes'
activerecord (5.2.3) lib/active_record/associations/has_many_through_association.rb:135:in `delete_records'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:398:in `remove_records'
activerecord (5.2.3) lib/active_record/associations/has_many_through_association.rb:108:in `remove_records'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:391:in `block in delete_or_destroy'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:135:in `block in transaction'
activerecord (5.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
activerecord (5.2.3) lib/active_record/transactions.rb:212:in `transaction'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:134:in `transaction'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:391:in `delete_or_destroy'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:189:in `delete'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:413:in `replace_records'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:251:in `block in replace'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:135:in `block in transaction'
activerecord (5.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
activerecord (5.2.3) lib/active_record/transactions.rb:212:in `transaction'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:134:in `transaction'
activerecord (5.2.3) lib/active_record/associations/collection_association.rb:251:in `replace'
composite_primary_keys (11.2.0) lib/composite_primary_keys/associations/collection_association.rb:26:in `ids_writer'
activerecord (5.2.3) lib/active_record/associations/builder/collection_association.rb:65:in `facility_ids='
```

I'm not sure if there is a good solution for this. I'm using the following patch to fix this now (of course I know in this case that CPK does not apply):

```ruby
require 'composite_primary_keys/associations/through_association'

module ActiveRecord
  module Associations
    module ThroughAssociation
      alias cpk_construct_join_attributes construct_join_attributes

      def construct_join_attributes(*records)
        if source_reflection.polymorphic?
          original_construct_join_attributes(*records)
        else
          cpk_construct_join_attributes(*records)
        end
      end
    end
  end
end
```

**Comment by cfis** [comment]
Interesting. Looks like we need to add a test case for this.  Thanks for the report.

**Comment by cfis** [comment]
Sorry for the very long delay. Better late than never I guess? Thanks for the report.
