### ISSUE TITLE
Update all fails with MySQL on 12.0.0rc5

### ISSUE THREAD

**Issue by adrientoub** [composite-primary-keys/composite_primary_keys#493]
Hello,

I have been trying to update Rails to 6.0.0 but I have an issue with this gem.
When using update_all on tables that are using `composite_primary_keys` I get an error: `You can't specify target table 'reference_codes' for update in FROM clause`.
I was able to reproduce it by launching your test suite on the latest commit 460807d on my machine.

Here is the test detail:
```
 13) Error:
TestUpdate#test_update_all:
ActiveRecord::StatementInvalid: Mysql2::Error: You can't specify target table 'reference_codes' for update in FROM clause
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:194:in `block (2 levels) in execute'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:193:in `block in execute'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:707:in `block (2 levels) in log'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:706:in `block in log'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:697:in `log'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:192:in `execute'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:39:in `execute'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:203:in `execute_and_free'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:65:in `block in exec_delete'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/mysql/database_statements.rb:64:in `exec_delete'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:170:in `update'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
    /home/username/composite_primary_keys/lib/composite_primary_keys/relation.rb:58:in `update_all'
    /home/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/querying.rb:21:in `update_all'
    /home/username/composite_primary_keys/test/test_update.rb:62:in `test_update_all'
```

I am available if you require more details.

**Comment by cfis** [comment]
I think this was fixed with #496
